/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-05-15 00:36:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cgm.hello_web_app.dao.ProductDAO;
import com.cgm.hello_web_app.dao.DbCon;
import com.cgm.hello_web_app.eitities.User;
import com.cgm.hello_web_app.eitities.Cart;
import com.cgm.hello_web_app.eitities.*;
import java.util.ArrayList;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1426003893000L));
    _jspx_dependants.put("jar:file:/C:/laptrinhlop/resfulweb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HelloWebApp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.cgm.hello_web_app.eitities");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.cgm.hello_web_app.dao.ProductDAO");
    _jspx_imports_classes.add("com.cgm.hello_web_app.eitities.User");
    _jspx_imports_classes.add("com.cgm.hello_web_app.dao.DbCon");
    _jspx_imports_classes.add("com.cgm.hello_web_app.eitities.Cart");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 




User auth =(User) request.getSession().getAttribute("auth");
if(auth!=null){
	request.setAttribute("auth", auth);
}
ArrayList<Cart> cart_list= (ArrayList<Cart>) session.getAttribute("cart-list");
ArrayList<Cart> cartProuduct = null;
if(cart_list != null) {
	
	ProductDAO pDao= new ProductDAO(DbCon.getConnection());
	cartProuduct = pDao.getCartProducts(cart_list);
      double total= pDao.getTotalPrice(cart_list);
	request.setAttribute("cart_list", cart_list);
	request.setAttribute("total", total);
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("	ustora by freshdesignweb.com\r\n");
      out.write("	Twitter: https://twitter.com/freshdesignweb\r\n");
      out.write("	URL: https://www.freshdesignweb.com/ustora/\r\n");
      out.write("-->\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Cart Page - Ustora Demo</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"header-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"user-menu\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-user\"></i> My Account</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-heart\"></i> Wishlist</a></li>\r\n");
      out.write("                            <li><a href=\"cart.jsp\"><i class=\"fa fa-user\"></i> My Cart</a></li>\r\n");
      out.write("                            <!-- <li><a href=\"checkout.html\"><i class=\"fa fa-user\"></i> Checkout</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-user\"></i> Login</a></li> -->\r\n");
      out.write("                            \r\n");
      out.write("                            ");
 if(request.getSession().getAttribute("auth") != null) { 
      out.write("\r\n");
      out.write("                            <li><a href=\"checkout.html\"><i class=\"fa fa-user\"></i> Checkout</a></li>\r\n");
      out.write("                            <li><a href=\"user-logout\"><i class=\"fa fa-user\"></i> Logout</a></li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li><a href=\"user-login\"><i class=\"fa fa-user\"></i> Login</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"header-right\">\r\n");
      out.write("                        <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("                            <li class=\"dropdown dropdown-small\">\r\n");
      out.write("                                <a data-toggle=\"dropdown\" data-hover=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><span class=\"key\">currency :</span><span class=\"value\">USD </span><b class=\"caret\"></b></a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"#\">USD</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">INR</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">GBP</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"dropdown dropdown-small\">\r\n");
      out.write("                                <a data-toggle=\"dropdown\" data-hover=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><span class=\"key\">language :</span><span class=\"value\">English </span><b class=\"caret\"></b></a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"#\">English</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">French</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">German</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End header area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"site-branding-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"logo\">\r\n");
      out.write("                        <h1><a href=\"./\"><img src=\"img/logo.png\"></a></h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"shopping-item\">\r\n");
      out.write("                        <a href=\"cart.html\">Cart - <span class=\"cart-amunt\">$ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(total>0)?total:0}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span><i class=\"fa fa-shopping-cart\"></i> <span class=\"badge badge-danger\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart_list.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End site branding area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mainmenu-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"navbar-collapse collapse\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav\">\r\n");
      out.write("                        <li><a href=\"home\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"shop\">Shop page</a></li>\r\n");
      out.write("                        <li><a href=\"single-product.html\">Single product</a></li>\r\n");
      out.write("                        <li class=\"active\"><a href=\"cart.html\">Cart</a></li>\r\n");
      out.write("                        <li><a href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Category</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Others</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End mainmenu area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"product-big-title-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"product-bit-title text-center\">\r\n");
      out.write("                        <h2>Shopping Cart</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End Page title area -->\r\n");
      out.write("         \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"single-product-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"single-sidebar\">\r\n");
      out.write("                        <h2 class=\"sidebar-title\">Search Products</h2>\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Search products...\">\r\n");
      out.write("                            <input type=\"submit\" value=\"Search\">\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"single-sidebar\">\r\n");
      out.write("                        <h2 class=\"sidebar-title\">Products</h2>\r\n");
      out.write("                        <div class=\"thubmnail-recent\">\r\n");
      out.write("                            <img src=\"img/product-thumb-1.jpg\" class=\"recent-thumb\" alt=\"\">\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-sidebar-price\">\r\n");
      out.write("                                <ins>$700.00</ins> <del>$800.00</del>\r\n");
      out.write("                            </div>                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"thubmnail-recent\">\r\n");
      out.write("                            <img src=\"img/product-thumb-1.jpg\" class=\"recent-thumb\" alt=\"\">\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-sidebar-price\">\r\n");
      out.write("                                <ins>$700.00</ins> <del>$800.00</del>\r\n");
      out.write("                            </div>                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"thubmnail-recent\">\r\n");
      out.write("                            <img src=\"img/product-thumb-1.jpg\" class=\"recent-thumb\" alt=\"\">\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-sidebar-price\">\r\n");
      out.write("                                <ins>$700.00</ins> <del>$800.00</del>\r\n");
      out.write("                            </div>                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"thubmnail-recent\">\r\n");
      out.write("                            <img src=\"img/product-thumb-1.jpg\" class=\"recent-thumb\" alt=\"\">\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-sidebar-price\">\r\n");
      out.write("                                <ins>$700.00</ins> <del>$800.00</del>\r\n");
      out.write("                            </div>                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"single-sidebar\">\r\n");
      out.write("                        <h2 class=\"sidebar-title\">Recent Posts</h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"product-content-right\">\r\n");
      out.write("                        <div class=\"woocommerce\">\r\n");
      out.write("                            <form method=\"post\" action=\"#\">\r\n");
      out.write("                                <table cellspacing=\"0\" class=\"shop_table cart\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th class=\"product-remove\">&nbsp;</th>\r\n");
      out.write("                                            <th class=\"product-thumbnail\">&nbsp;</th>\r\n");
      out.write("                                            <th class=\"product-name\">Product</th>\r\n");
      out.write("                                            <th class=\"product-price\">Price</th>\r\n");
      out.write("                                            <th class=\"product-quantity\">Quantity</th>\r\n");
      out.write("                                            <th class=\"product-subtotal\">Total</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                    \r\n");
      out.write("                                    ");
 if (cart_list != null) {
    for (Cart c : cartProuduct) { 
      out.write("\r\n");
      out.write("        <tr class=\"cart_item\">\r\n");
      out.write("            <td class=\"product-remove\">\r\n");
      out.write("                <a title=\"Remove this item\" class=\"remove\" href=\"remove-cart?id=");
      out.print(c.getId() );
      out.write("\">×</a> \r\n");
      out.write("            </td>\r\n");
      out.write("\r\n");
      out.write("            <td class=\"product-thumbnail\">\r\n");
      out.write("                <a href=\"single-product.html\"><img width=\"145\" height=\"145\" alt=\"poster_1_up\" class=\"shop_thumbnail\" src=\"");
      out.print( c.getImage() );
      out.write("\"></a>\r\n");
      out.write("            </td>\r\n");
      out.write("\r\n");
      out.write("            <td class=\"product-name\">\r\n");
      out.write("                <a href=\"single-product.html\">");
      out.print( c.getName() );
      out.write("</a> \r\n");
      out.write("            </td>\r\n");
      out.write("\r\n");
      out.write("            <td class=\"product-price\">\r\n");
      out.write("                <span class=\"amount\">£");
      out.print( c.getPrice() );
      out.write("</span> \r\n");
      out.write("            </td>\r\n");
      out.write("\r\n");
      out.write("            <td class=\"product-quantity\">\r\n");
      out.write("                <div class=\"quantity buttons_added\">\r\n");
      out.write("                  <a href=\"quantity-inc-dec?action=dec&id=");
      out.print(c.getId() );
      out.write("\"  class=\"btn btn-success btn-xs minus\">-</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"number\" size=\"4\" class=\"input-text qty text\" title=\"Qty\" value=\"");
      out.print( c.getQuantity() );
      out.write("\" min=\"0\" step=\"1\">\r\n");
      out.write("                    \r\n");
      out.write("                      <a href=\"quantity-inc-dec?action=inc&id=");
      out.print(c.getId() );
      out.write("\"  class=\"btn btn-success btn-xs minus\">+</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </td>\r\n");
      out.write("\r\n");
      out.write("            <td class=\"product-subtotal\">\r\n");
      out.write("                <span class=\"amount\">£");
      out.print( c.getPrice() * c.getQuantity() );
      out.write("</span> \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    ");
 }
} 
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                        \r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"actions\" colspan=\"6\">\r\n");
      out.write("                                                <div class=\"coupon\">\r\n");
      out.write("                                                    <label for=\"coupon_code\">Coupon:</label>\r\n");
      out.write("                                                    <input type=\"text\" placeholder=\"Coupon code\" value=\"\" id=\"coupon_code\" class=\"input-text\" name=\"coupon_code\">\r\n");
      out.write("                                                    <input type=\"submit\" value=\"Apply Coupon\" name=\"apply_coupon\" class=\"button\">\r\n");
      out.write("                                                    \r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <input type=\"submit\" value=\"Update Cart\" name=\"update_cart\" class=\"button\">\r\n");
      out.write("                                                <a href=\"buy-now\" class=\"btn btn-primary\">CheckOut</a>\r\n");
      out.write("                                                \r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"cart-collaterals\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"cross-sells\">\r\n");
      out.write("                                <h2>You may be interested in...</h2>\r\n");
      out.write("                                <ul class=\"products\">\r\n");
      out.write("                                    <li class=\"product\">\r\n");
      out.write("                                        <a href=\"single-product.html\">\r\n");
      out.write("                                            <img width=\"325\" height=\"325\" alt=\"T_4_front\" class=\"attachment-shop_catalog wp-post-image\" src=\"img/product-2.jpg\">\r\n");
      out.write("                                            <h3>Ship Your Idea</h3>\r\n");
      out.write("                                            <span class=\"price\"><span class=\"amount\">£20.00</span></span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("\r\n");
      out.write("                                        <a class=\"add_to_cart_button\" data-quantity=\"1\" data-product_sku=\"\" data-product_id=\"22\" rel=\"nofollow\" href=\"single-product.html\">Select options</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("\r\n");
      out.write("                                    <li class=\"product\">\r\n");
      out.write("                                        <a href=\"single-product.html\">\r\n");
      out.write("                                            <img width=\"325\" height=\"325\" alt=\"T_4_front\" class=\"attachment-shop_catalog wp-post-image\" src=\"img/product-4.jpg\">\r\n");
      out.write("                                            <h3>Ship Your Idea</h3>\r\n");
      out.write("                                            <span class=\"price\"><span class=\"amount\">£20.00</span></span>\r\n");
      out.write("                                        </a>\r\n");
      out.write("\r\n");
      out.write("                                        <a class=\"add_to_cart_button\" data-quantity=\"1\" data-product_sku=\"\" data-product_id=\"22\" rel=\"nofollow\" href=\"single-product.html\">Select options</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"cart_totals \">\r\n");
      out.write("                                <h2>Cart Totals</h2>\r\n");
      out.write("\r\n");
      out.write("                                <table cellspacing=\"0\">\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        <tr class=\"cart-subtotal\">\r\n");
      out.write("                                            <th>Cart Subtotal</th>\r\n");
      out.write("                                            <td><span class=\"amount\">£15.00</span></td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("\r\n");
      out.write("                                        <tr class=\"shipping\">\r\n");
      out.write("                                            <th>Shipping and Handling</th>\r\n");
      out.write("                                            <td>Free Shipping</td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("\r\n");
      out.write("                                        <tr class=\"order-total\">\r\n");
      out.write("                                            <th>Order Total</th>\r\n");
      out.write("                                            <td><strong><span class=\"amount\">£15.00</span></strong> </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <form method=\"post\" action=\"#\" class=\"shipping_calculator\">\r\n");
      out.write("                                <h2><a class=\"shipping-calculator-button\" data-toggle=\"collapse\" href=\"#calcalute-shipping-wrap\" aria-expanded=\"false\" aria-controls=\"calcalute-shipping-wrap\">Calculate Shipping</a></h2>\r\n");
      out.write("\r\n");
      out.write("                                <section id=\"calcalute-shipping-wrap\" class=\"shipping-calculator-form collapse\">\r\n");
      out.write("\r\n");
      out.write("                                <p class=\"form-row form-row-wide\">\r\n");
      out.write("                                <select rel=\"calc_shipping_state\" class=\"country_to_state\" id=\"calc_shipping_country\" name=\"calc_shipping_country\">\r\n");
      out.write("                                    <option value=\"\">Select a country…</option>\r\n");
      out.write("                                    <option value=\"AX\">Åland Islands</option>\r\n");
      out.write("                                    <option value=\"AF\">Afghanistan</option>\r\n");
      out.write("                                    <option value=\"AL\">Albania</option>\r\n");
      out.write("                                    <option value=\"DZ\">Algeria</option>\r\n");
      out.write("                                    <option value=\"AD\">Andorra</option>\r\n");
      out.write("                                    <option value=\"AO\">Angola</option>\r\n");
      out.write("                                    <option value=\"AI\">Anguilla</option>\r\n");
      out.write("                                    <option value=\"AQ\">Antarctica</option>\r\n");
      out.write("                                    <option value=\"AG\">Antigua and Barbuda</option>\r\n");
      out.write("                                    <option value=\"AR\">Argentina</option>\r\n");
      out.write("                                    <option value=\"AM\">Armenia</option>\r\n");
      out.write("                                    <option value=\"AW\">Aruba</option>\r\n");
      out.write("                                    <option value=\"AU\">Australia</option>\r\n");
      out.write("                                    <option value=\"AT\">Austria</option>\r\n");
      out.write("                                    <option value=\"AZ\">Azerbaijan</option>\r\n");
      out.write("                                    <option value=\"BS\">Bahamas</option>\r\n");
      out.write("                                    <option value=\"BH\">Bahrain</option>\r\n");
      out.write("                                    <option value=\"BD\">Bangladesh</option>\r\n");
      out.write("                                    <option value=\"BB\">Barbados</option>\r\n");
      out.write("                                    <option value=\"BY\">Belarus</option>\r\n");
      out.write("                                    <option value=\"PW\">Belau</option>\r\n");
      out.write("                                    <option value=\"BE\">Belgium</option>\r\n");
      out.write("                                    <option value=\"BZ\">Belize</option>\r\n");
      out.write("                                    <option value=\"BJ\">Benin</option>\r\n");
      out.write("                                    <option value=\"BM\">Bermuda</option>\r\n");
      out.write("                                    <option value=\"BT\">Bhutan</option>\r\n");
      out.write("                                    <option value=\"BO\">Bolivia</option>\r\n");
      out.write("                                    <option value=\"BQ\">Bonaire, Saint Eustatius and Saba</option>\r\n");
      out.write("                                    <option value=\"BA\">Bosnia and Herzegovina</option>\r\n");
      out.write("                                    <option value=\"BW\">Botswana</option>\r\n");
      out.write("                                    <option value=\"BV\">Bouvet Island</option>\r\n");
      out.write("                                    <option value=\"BR\">Brazil</option>\r\n");
      out.write("                                    <option value=\"IO\">British Indian Ocean Territory</option>\r\n");
      out.write("                                    <option value=\"VG\">British Virgin Islands</option>\r\n");
      out.write("                                    <option value=\"BN\">Brunei</option>\r\n");
      out.write("                                    <option value=\"BG\">Bulgaria</option>\r\n");
      out.write("                                    <option value=\"BF\">Burkina Faso</option>\r\n");
      out.write("                                    <option value=\"BI\">Burundi</option>\r\n");
      out.write("                                    <option value=\"KH\">Cambodia</option>\r\n");
      out.write("                                    <option value=\"CM\">Cameroon</option>\r\n");
      out.write("                                    <option value=\"CA\">Canada</option>\r\n");
      out.write("                                    <option value=\"CV\">Cape Verde</option>\r\n");
      out.write("                                    <option value=\"KY\">Cayman Islands</option>\r\n");
      out.write("                                    <option value=\"CF\">Central African Republic</option>\r\n");
      out.write("                                    <option value=\"TD\">Chad</option>\r\n");
      out.write("                                    <option value=\"CL\">Chile</option>\r\n");
      out.write("                                    <option value=\"CN\">China</option>\r\n");
      out.write("                                    <option value=\"CX\">Christmas Island</option>\r\n");
      out.write("                                    <option value=\"CC\">Cocos (Keeling) Islands</option>\r\n");
      out.write("                                    <option value=\"CO\">Colombia</option>\r\n");
      out.write("                                    <option value=\"KM\">Comoros</option>\r\n");
      out.write("                                    <option value=\"CG\">Congo (Brazzaville)</option>\r\n");
      out.write("                                    <option value=\"CD\">Congo (Kinshasa)</option>\r\n");
      out.write("                                    <option value=\"CK\">Cook Islands</option>\r\n");
      out.write("                                    <option value=\"CR\">Costa Rica</option>\r\n");
      out.write("                                    <option value=\"HR\">Croatia</option>\r\n");
      out.write("                                    <option value=\"CU\">Cuba</option>\r\n");
      out.write("                                    <option value=\"CW\">CuraÇao</option>\r\n");
      out.write("                                    <option value=\"CY\">Cyprus</option>\r\n");
      out.write("                                    <option value=\"CZ\">Czech Republic</option>\r\n");
      out.write("                                    <option value=\"DK\">Denmark</option>\r\n");
      out.write("                                    <option value=\"DJ\">Djibouti</option>\r\n");
      out.write("                                    <option value=\"DM\">Dominica</option>\r\n");
      out.write("                                    <option value=\"DO\">Dominican Republic</option>\r\n");
      out.write("                                    <option value=\"EC\">Ecuador</option>\r\n");
      out.write("                                    <option value=\"EG\">Egypt</option>\r\n");
      out.write("                                    <option value=\"SV\">El Salvador</option>\r\n");
      out.write("                                    <option value=\"GQ\">Equatorial Guinea</option>\r\n");
      out.write("                                    <option value=\"ER\">Eritrea</option>\r\n");
      out.write("                                    <option value=\"EE\">Estonia</option>\r\n");
      out.write("                                    <option value=\"ET\">Ethiopia</option>\r\n");
      out.write("                                    <option value=\"FK\">Falkland Islands</option>\r\n");
      out.write("                                    <option value=\"FO\">Faroe Islands</option>\r\n");
      out.write("                                    <option value=\"FJ\">Fiji</option>\r\n");
      out.write("                                    <option value=\"FI\">Finland</option>\r\n");
      out.write("                                    <option value=\"FR\">France</option>\r\n");
      out.write("                                    <option value=\"GF\">French Guiana</option>\r\n");
      out.write("                                    <option value=\"PF\">French Polynesia</option>\r\n");
      out.write("                                    <option value=\"TF\">French Southern Territories</option>\r\n");
      out.write("                                    <option value=\"GA\">Gabon</option>\r\n");
      out.write("                                    <option value=\"GM\">Gambia</option>\r\n");
      out.write("                                    <option value=\"GE\">Georgia</option>\r\n");
      out.write("                                    <option value=\"DE\">Germany</option>\r\n");
      out.write("                                    <option value=\"GH\">Ghana</option>\r\n");
      out.write("                                    <option value=\"GI\">Gibraltar</option>\r\n");
      out.write("                                    <option value=\"GR\">Greece</option>\r\n");
      out.write("                                    <option value=\"GL\">Greenland</option>\r\n");
      out.write("                                    <option value=\"GD\">Grenada</option>\r\n");
      out.write("                                    <option value=\"GP\">Guadeloupe</option>\r\n");
      out.write("                                    <option value=\"GT\">Guatemala</option>\r\n");
      out.write("                                    <option value=\"GG\">Guernsey</option>\r\n");
      out.write("                                    <option value=\"GN\">Guinea</option>\r\n");
      out.write("                                    <option value=\"GW\">Guinea-Bissau</option>\r\n");
      out.write("                                    <option value=\"GY\">Guyana</option>\r\n");
      out.write("                                    <option value=\"HT\">Haiti</option>\r\n");
      out.write("                                    <option value=\"HM\">Heard Island and McDonald Islands</option>\r\n");
      out.write("                                    <option value=\"HN\">Honduras</option>\r\n");
      out.write("                                    <option value=\"HK\">Hong Kong</option>\r\n");
      out.write("                                    <option value=\"HU\">Hungary</option>\r\n");
      out.write("                                    <option value=\"IS\">Iceland</option>\r\n");
      out.write("                                    <option value=\"IN\">India</option>\r\n");
      out.write("                                    <option value=\"ID\">Indonesia</option>\r\n");
      out.write("                                    <option value=\"IR\">Iran</option>\r\n");
      out.write("                                    <option value=\"IQ\">Iraq</option>\r\n");
      out.write("                                    <option value=\"IM\">Isle of Man</option>\r\n");
      out.write("                                    <option value=\"IL\">Israel</option>\r\n");
      out.write("                                    <option value=\"IT\">Italy</option>\r\n");
      out.write("                                    <option value=\"CI\">Ivory Coast</option>\r\n");
      out.write("                                    <option value=\"JM\">Jamaica</option>\r\n");
      out.write("                                    <option value=\"JP\">Japan</option>\r\n");
      out.write("                                    <option value=\"JE\">Jersey</option>\r\n");
      out.write("                                    <option value=\"JO\">Jordan</option>\r\n");
      out.write("                                    <option value=\"KZ\">Kazakhstan</option>\r\n");
      out.write("                                    <option value=\"KE\">Kenya</option>\r\n");
      out.write("                                    <option value=\"KI\">Kiribati</option>\r\n");
      out.write("                                    <option value=\"KW\">Kuwait</option>\r\n");
      out.write("                                    <option value=\"KG\">Kyrgyzstan</option>\r\n");
      out.write("                                    <option value=\"LA\">Laos</option>\r\n");
      out.write("                                    <option value=\"LV\">Latvia</option>\r\n");
      out.write("                                    <option value=\"LB\">Lebanon</option>\r\n");
      out.write("                                    <option value=\"LS\">Lesotho</option>\r\n");
      out.write("                                    <option value=\"LR\">Liberia</option>\r\n");
      out.write("                                    <option value=\"LY\">Libya</option>\r\n");
      out.write("                                    <option value=\"LI\">Liechtenstein</option>\r\n");
      out.write("                                    <option value=\"LT\">Lithuania</option>\r\n");
      out.write("                                    <option value=\"LU\">Luxembourg</option>\r\n");
      out.write("                                    <option value=\"MO\">Macao S.A.R., China</option>\r\n");
      out.write("                                    <option value=\"MK\">Macedonia</option>\r\n");
      out.write("                                    <option value=\"MG\">Madagascar</option>\r\n");
      out.write("                                    <option value=\"MW\">Malawi</option>\r\n");
      out.write("                                    <option value=\"MY\">Malaysia</option>\r\n");
      out.write("                                    <option value=\"MV\">Maldives</option>\r\n");
      out.write("                                    <option value=\"ML\">Mali</option>\r\n");
      out.write("                                    <option value=\"MT\">Malta</option>\r\n");
      out.write("                                    <option value=\"MH\">Marshall Islands</option>\r\n");
      out.write("                                    <option value=\"MQ\">Martinique</option>\r\n");
      out.write("                                    <option value=\"MR\">Mauritania</option>\r\n");
      out.write("                                    <option value=\"MU\">Mauritius</option>\r\n");
      out.write("                                    <option value=\"YT\">Mayotte</option>\r\n");
      out.write("                                    <option value=\"MX\">Mexico</option>\r\n");
      out.write("                                    <option value=\"FM\">Micronesia</option>\r\n");
      out.write("                                    <option value=\"MD\">Moldova</option>\r\n");
      out.write("                                    <option value=\"MC\">Monaco</option>\r\n");
      out.write("                                    <option value=\"MN\">Mongolia</option>\r\n");
      out.write("                                    <option value=\"ME\">Montenegro</option>\r\n");
      out.write("                                    <option value=\"MS\">Montserrat</option>\r\n");
      out.write("                                    <option value=\"MA\">Morocco</option>\r\n");
      out.write("                                    <option value=\"MZ\">Mozambique</option>\r\n");
      out.write("                                    <option value=\"MM\">Myanmar</option>\r\n");
      out.write("                                    <option value=\"NA\">Namibia</option>\r\n");
      out.write("                                    <option value=\"NR\">Nauru</option>\r\n");
      out.write("                                    <option value=\"NP\">Nepal</option>\r\n");
      out.write("                                    <option value=\"NL\">Netherlands</option>\r\n");
      out.write("                                    <option value=\"AN\">Netherlands Antilles</option>\r\n");
      out.write("                                    <option value=\"NC\">New Caledonia</option>\r\n");
      out.write("                                    <option value=\"NZ\">New Zealand</option>\r\n");
      out.write("                                    <option value=\"NI\">Nicaragua</option>\r\n");
      out.write("                                    <option value=\"NE\">Niger</option>\r\n");
      out.write("                                    <option value=\"NG\">Nigeria</option>\r\n");
      out.write("                                    <option value=\"NU\">Niue</option>\r\n");
      out.write("                                    <option value=\"NF\">Norfolk Island</option>\r\n");
      out.write("                                    <option value=\"KP\">North Korea</option>\r\n");
      out.write("                                    <option value=\"NO\">Norway</option>\r\n");
      out.write("                                    <option value=\"OM\">Oman</option>\r\n");
      out.write("                                    <option value=\"PK\">Pakistan</option>\r\n");
      out.write("                                    <option value=\"PS\">Palestinian Territory</option>\r\n");
      out.write("                                    <option value=\"PA\">Panama</option>\r\n");
      out.write("                                    <option value=\"PG\">Papua New Guinea</option>\r\n");
      out.write("                                    <option value=\"PY\">Paraguay</option>\r\n");
      out.write("                                    <option value=\"PE\">Peru</option>\r\n");
      out.write("                                    <option value=\"PH\">Philippines</option>\r\n");
      out.write("                                    <option value=\"PN\">Pitcairn</option>\r\n");
      out.write("                                    <option value=\"PL\">Poland</option>\r\n");
      out.write("                                    <option value=\"PT\">Portugal</option>\r\n");
      out.write("                                    <option value=\"QA\">Qatar</option>\r\n");
      out.write("                                    <option value=\"IE\">Republic of Ireland</option>\r\n");
      out.write("                                    <option value=\"RE\">Reunion</option>\r\n");
      out.write("                                    <option value=\"RO\">Romania</option>\r\n");
      out.write("                                    <option value=\"RU\">Russia</option>\r\n");
      out.write("                                    <option value=\"RW\">Rwanda</option>\r\n");
      out.write("                                    <option value=\"ST\">São Tomé and Príncipe</option>\r\n");
      out.write("                                    <option value=\"BL\">Saint Barthélemy</option>\r\n");
      out.write("                                    <option value=\"SH\">Saint Helena</option>\r\n");
      out.write("                                    <option value=\"KN\">Saint Kitts and Nevis</option>\r\n");
      out.write("                                    <option value=\"LC\">Saint Lucia</option>\r\n");
      out.write("                                    <option value=\"SX\">Saint Martin (Dutch part)</option>\r\n");
      out.write("                                    <option value=\"MF\">Saint Martin (French part)</option>\r\n");
      out.write("                                    <option value=\"PM\">Saint Pierre and Miquelon</option>\r\n");
      out.write("                                    <option value=\"VC\">Saint Vincent and the Grenadines</option>\r\n");
      out.write("                                    <option value=\"SM\">San Marino</option>\r\n");
      out.write("                                    <option value=\"SA\">Saudi Arabia</option>\r\n");
      out.write("                                    <option value=\"SN\">Senegal</option>\r\n");
      out.write("                                    <option value=\"RS\">Serbia</option>\r\n");
      out.write("                                    <option value=\"SC\">Seychelles</option>\r\n");
      out.write("                                    <option value=\"SL\">Sierra Leone</option>\r\n");
      out.write("                                    <option value=\"SG\">Singapore</option>\r\n");
      out.write("                                    <option value=\"SK\">Slovakia</option>\r\n");
      out.write("                                    <option value=\"SI\">Slovenia</option>\r\n");
      out.write("                                    <option value=\"SB\">Solomon Islands</option>\r\n");
      out.write("                                    <option value=\"SO\">Somalia</option>\r\n");
      out.write("                                    <option value=\"ZA\">South Africa</option>\r\n");
      out.write("                                    <option value=\"GS\">South Georgia/Sandwich Islands</option>\r\n");
      out.write("                                    <option value=\"KR\">South Korea</option>\r\n");
      out.write("                                    <option value=\"SS\">South Sudan</option>\r\n");
      out.write("                                    <option value=\"ES\">Spain</option>\r\n");
      out.write("                                    <option value=\"LK\">Sri Lanka</option>\r\n");
      out.write("                                    <option value=\"SD\">Sudan</option>\r\n");
      out.write("                                    <option value=\"SR\">Suriname</option>\r\n");
      out.write("                                    <option value=\"SJ\">Svalbard and Jan Mayen</option>\r\n");
      out.write("                                    <option value=\"SZ\">Swaziland</option>\r\n");
      out.write("                                    <option value=\"SE\">Sweden</option>\r\n");
      out.write("                                    <option value=\"CH\">Switzerland</option>\r\n");
      out.write("                                    <option value=\"SY\">Syria</option>\r\n");
      out.write("                                    <option value=\"TW\">Taiwan</option>\r\n");
      out.write("                                    <option value=\"TJ\">Tajikistan</option>\r\n");
      out.write("                                    <option value=\"TZ\">Tanzania</option>\r\n");
      out.write("                                    <option value=\"TH\">Thailand</option>\r\n");
      out.write("                                    <option value=\"TL\">Timor-Leste</option>\r\n");
      out.write("                                    <option value=\"TG\">Togo</option>\r\n");
      out.write("                                    <option value=\"TK\">Tokelau</option>\r\n");
      out.write("                                    <option value=\"TO\">Tonga</option>\r\n");
      out.write("                                    <option value=\"TT\">Trinidad and Tobago</option>\r\n");
      out.write("                                    <option value=\"TN\">Tunisia</option>\r\n");
      out.write("                                    <option value=\"TR\">Turkey</option>\r\n");
      out.write("                                    <option value=\"TM\">Turkmenistan</option>\r\n");
      out.write("                                    <option value=\"TC\">Turks and Caicos Islands</option>\r\n");
      out.write("                                    <option value=\"TV\">Tuvalu</option>\r\n");
      out.write("                                    <option value=\"UG\">Uganda</option>\r\n");
      out.write("                                    <option value=\"UA\">Ukraine</option>\r\n");
      out.write("                                    <option value=\"AE\">United Arab Emirates</option>\r\n");
      out.write("                                    <option selected=\"selected\" value=\"GB\">United Kingdom (UK)</option>\r\n");
      out.write("                                    <option value=\"US\">United States (US)</option>\r\n");
      out.write("                                    <option value=\"UY\">Uruguay</option>\r\n");
      out.write("                                    <option value=\"UZ\">Uzbekistan</option>\r\n");
      out.write("                                    <option value=\"VU\">Vanuatu</option>\r\n");
      out.write("                                    <option value=\"VA\">Vatican</option>\r\n");
      out.write("                                    <option value=\"VE\">Venezuela</option>\r\n");
      out.write("                                    <option value=\"VN\">Vietnam</option>\r\n");
      out.write("                                    <option value=\"WF\">Wallis and Futuna</option>\r\n");
      out.write("                                    <option value=\"EH\">Western Sahara</option>\r\n");
      out.write("                                    <option value=\"WS\">Western Samoa</option>\r\n");
      out.write("                                    <option value=\"YE\">Yemen</option>\r\n");
      out.write("                                    <option value=\"ZM\">Zambia</option>\r\n");
      out.write("                                    <option value=\"ZW\">Zimbabwe</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                                <p class=\"form-row form-row-wide\"><input type=\"text\" id=\"calc_shipping_state\" name=\"calc_shipping_state\" placeholder=\"State / county\" value=\"\" class=\"input-text\"> </p>\r\n");
      out.write("\r\n");
      out.write("                                <p class=\"form-row form-row-wide\"><input type=\"text\" id=\"calc_shipping_postcode\" name=\"calc_shipping_postcode\" placeholder=\"Postcode / Zip\" value=\"\" class=\"input-text\"></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <p><button class=\"button\" value=\"1\" name=\"calc_shipping\" type=\"submit\">Update Totals</button></p>\r\n");
      out.write("\r\n");
      out.write("                                </section>\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>                        \r\n");
      out.write("                    </div>                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-top-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer-about-us\">\r\n");
      out.write("                        <h2>u<span>Stora</span></h2>\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>\r\n");
      out.write("                        <div class=\"footer-social\">\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-youtube\"></i></a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer-menu\">\r\n");
      out.write("                        <h2 class=\"footer-wid-title\">User Navigation </h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">My account</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Order history</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Wishlist</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Vendor contact</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Front page</a></li>\r\n");
      out.write("                        </ul>                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer-menu\">\r\n");
      out.write("                        <h2 class=\"footer-wid-title\">Categories</h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Mobile Phone</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Home accesseries</a></li>\r\n");
      out.write("                            <li><a href=\"#\">LED TV</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Computer</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Gadets</a></li>\r\n");
      out.write("                        </ul>                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer-newsletter\">\r\n");
      out.write("                        <h2 class=\"footer-wid-title\">Newsletter</h2>\r\n");
      out.write("                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>\r\n");
      out.write("                        <div class=\"newsletter-form\">\r\n");
      out.write("                            <form action=\"#\">\r\n");
      out.write("                                <input type=\"email\" placeholder=\"Type your email\">\r\n");
      out.write("                                <input type=\"submit\" value=\"Subscribe\">\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End footer top area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"footer-bottom-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"copyright\">\r\n");
      out.write("                        <p>&copy; 2015 uCommerce. All Rights Reserved. <a href=\"http://www.freshdesignweb.com\" target=\"_blank\">freshDesignweb.com</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"footer-card-icon\">\r\n");
      out.write("                        <i class=\"fa fa-cc-discover\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-mastercard\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-paypal\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-visa\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End footer bottom area -->\r\n");
      out.write("   \r\n");
      out.write("    <!-- Latest jQuery form server -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap JS form CDN -->\r\n");
      out.write("    <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery sticky menu -->\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.sticky.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery easing -->\r\n");
      out.write("    <script src=\"js/jquery.easing.1.3.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Script -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
