/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-05-15 01:57:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cgm.hello_web_app.eitities.User;
import com.cgm.hello_web_app.dao.UserDao;
import com.cgm.hello_web_app.dao.DbCon;
import java.util.List;
import com.cgm.hello_web_app.eitities.*;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1426003893000L));
    _jspx_dependants.put("jar:file:/C:/laptrinhlop/resfulweb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HelloWebApp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.cgm.hello_web_app.eitities");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.cgm.hello_web_app.dao.UserDao");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.cgm.hello_web_app.eitities.User");
    _jspx_imports_classes.add("com.cgm.hello_web_app.dao.DbCon");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
User auth =(User) request.getSession().getAttribute("auth");
if(auth!=null){
	request.setAttribute("auth", auth);
	 response.sendRedirect("loginreal.jsp");
     return; // Stop further execution
}


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("	ustora by freshdesignweb.com\r\n");
      out.write("	Twitter: https://twitter.com/freshdesignweb\r\n");
      out.write("	URL: https://www.freshdesignweb.com/ustora/\r\n");
      out.write("-->\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Checkout Page - Ustora Demo</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("	ustora by freshdesignweb.com\r\n");
      out.write("	Twitter: https://twitter.com/freshdesignweb\r\n");
      out.write("	URL: https://www.freshdesignweb.com/ustora/\r\n");
      out.write("-->\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Checkout Page - Ustora Demo</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"header-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"user-menu\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-user\"></i> My Account</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-heart\"></i> Wishlist</a></li>\r\n");
      out.write("                            <li><a href=\"cart.html\"><i class=\"fa fa-user\"></i> My Cart</a></li>\r\n");
      out.write("                            ");
 if(request.getSession().getAttribute("auth") != null) { 
      out.write("\r\n");
      out.write("                            <li><a href=\"checkout.html\"><i class=\"fa fa-user\"></i> Checkout</a></li>\r\n");
      out.write("                            <li><a href=\"user-logout\"><i class=\"fa fa-user\"></i> Logout</a></li>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                            <li><a href=\"user-login\"><i class=\"fa fa-user\"></i> Login</a></li>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"header-right\">\r\n");
      out.write("                        <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("                            <li class=\"dropdown dropdown-small\">\r\n");
      out.write("                                <a data-toggle=\"dropdown\" data-hover=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><span class=\"key\">currency :</span><span class=\"value\">USD </span><b class=\"caret\"></b></a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"#\">USD</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">INR</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">GBP</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"dropdown dropdown-small\">\r\n");
      out.write("                                <a data-toggle=\"dropdown\" data-hover=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><span class=\"key\">language :</span><span class=\"value\">English </span><b class=\"caret\"></b></a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"#\">English</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">French</a></li>\r\n");
      out.write("                                    <li><a href=\"#\">German</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End header area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"site-branding-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"logo\">\r\n");
      out.write("                        <h1><a href=\"./\"><img src=\"img/logo.png\"></a></h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                    <div class=\"shopping-item\">\r\n");
      out.write("                        <a href=\"cart.html\">Cart - <span class=\"cart-amunt\">$100</span> <i class=\"fa fa-shopping-cart\"></i> <span class=\"product-count\">5</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End site branding area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"mainmenu-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"navbar-header\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div> \r\n");
      out.write("                <div class=\"navbar-collapse collapse\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav\">\r\n");
      out.write("                        <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"shop.html\">Shop page</a></li>\r\n");
      out.write("                        <li><a href=\"single-product.html\">Single product</a></li>\r\n");
      out.write("                        <li><a href=\"cart.html\">Cart</a></li>\r\n");
      out.write("                        <li class=\"active\"><a href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Category</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Others</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div> <!-- End mainmenu area -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"product-big-title-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"product-bit-title text-center\">\r\n");
      out.write("                        <h2>Shopping Cart</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"single-product-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"single-sidebar\">\r\n");
      out.write("                        <h2 class=\"sidebar-title\">Search Products</h2>\r\n");
      out.write("                        <form action=\"\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Search products...\">\r\n");
      out.write("                            <input type=\"submit\" value=\"Search\">\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"single-sidebar\">\r\n");
      out.write("                        <h2 class=\"sidebar-title\">Products</h2>\r\n");
      out.write("                        <div class=\"thubmnail-recent\">\r\n");
      out.write("                            <img src=\"img/product-thumb-1.jpg\" class=\"recent-thumb\" alt=\"\">\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-sidebar-price\">\r\n");
      out.write("                                <ins>$700.00</ins> <del>$100.00</del>\r\n");
      out.write("                            </div>                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"thubmnail-recent\">\r\n");
      out.write("                            <img src=\"img/product-thumb-1.jpg\" class=\"recent-thumb\" alt=\"\">\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-sidebar-price\">\r\n");
      out.write("                                <ins>$700.00</ins> <del>$100.00</del>\r\n");
      out.write("                            </div>                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"thubmnail-recent\">\r\n");
      out.write("                            <img src=\"img/product-thumb-1.jpg\" class=\"recent-thumb\" alt=\"\">\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-sidebar-price\">\r\n");
      out.write("                                <ins>$700.00</ins> <del>$100.00</del>\r\n");
      out.write("                            </div>                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"thubmnail-recent\">\r\n");
      out.write("                            <img src=\"img/product-thumb-1.jpg\" class=\"recent-thumb\" alt=\"\">\r\n");
      out.write("                            <h2><a href=\"single-product.html\">Sony Smart TV - 2015</a></h2>\r\n");
      out.write("                            <div class=\"product-sidebar-price\">\r\n");
      out.write("                                <ins>$700.00</ins> <del>$100.00</del>\r\n");
      out.write("                            </div>                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"single-sidebar\">\r\n");
      out.write("                        <h2 class=\"sidebar-title\">Recent Posts</h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"single-product.html\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                            <li><a href=\"single-product.html\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                            <li><a href=\"single-product.html\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                            <li><a href=\"single-product.html\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                            <li><a href=\"single-product.html\">Sony Smart TV - 2015</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"product-content-right\">\r\n");
      out.write("                        <div class=\"woocommerce\">\r\n");
      out.write("                            <div class=\"woocommerce-info\">Returning customer? <a class=\"showlogin\" data-toggle=\"collapse\" href=\"#login-form-wrap\" aria-expanded=\"false\" aria-controls=\"login-form-wrap\">Click here to login</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <form id=\"login-form-wrap\" class=\"login collapse\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <p>If you have shopped with us before, please enter your details in the boxes below. If you are a new customer please proceed to the Billing &amp; Shipping section.</p>\r\n");
      out.write("\r\n");
      out.write("                                <p class=\"form-row form-row-first\">\r\n");
      out.write("                                    <label for=\"username\">Username or email <span class=\"required\">*</span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <input type=\"text\" id=\"username\" name=\"username\" class=\"input-text\">\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <p class=\"form-row form-row-last\">\r\n");
      out.write("                                    <label for=\"password\">Password <span class=\"required\">*</span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <input type=\"password\" id=\"password\" name=\"password\" class=\"input-text\">\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <p class=\"form-row\">\r\n");
      out.write("                                    <input type=\"submit\" value=\"Login\" name=\"login\" class=\"button\">\r\n");
      out.write("                                    <label class=\"inline\" for=\"rememberme\"><input type=\"checkbox\" value=\"forever\" id=\"rememberme\" name=\"rememberme\"> Remember me </label>\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <p class=\"lost_password\">\r\n");
      out.write("                                    <a href=\"#\">Lost your password?</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"clear\"></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"woocommerce-info\">Have a coupon? <a class=\"showcoupon\" data-toggle=\"collapse\" href=\"#coupon-collapse-wrap\" aria-expanded=\"false\" aria-controls=\"coupon-collapse-wrap\">Click here to enter your code</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <form id=\"coupon-collapse-wrap\" method=\"post\" class=\"checkout_coupon collapse\">\r\n");
      out.write("\r\n");
      out.write("                                <p class=\"form-row form-row-first\">\r\n");
      out.write("                                    <input type=\"text\" value=\"\" id=\"coupon_code\" placeholder=\"Coupon code\" class=\"input-text\" name=\"coupon_code\">\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                                <p class=\"form-row form-row-last\">\r\n");
      out.write("                                    <input type=\"submit\" value=\"Apply Coupon\" name=\"apply_coupon\" class=\"button\">\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"clear\"></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                            \r\n");
      out.write("                 ");


     int id=Integer.parseInt(request.getParameter("id"));

    UserDao dao = new UserDao(DbCon.getConnection());
    User u=dao.getUsertId(id);

      out.write("\r\n");
      out.write("<form enctype=\"multipart/form-data\" action=\"#\" class=\"checkout\" method=\"post\" name=\"checkout\">\r\n");
      out.write("\r\n");
      out.write("    <div id=\"customer_details\" class=\"col2-set\">\r\n");
      out.write("        <div class=\"col-1\">\r\n");
      out.write("            <div class=\"woocommerce-billing-fields\">\r\n");
      out.write("                <h3>Billing Details</h3>\r\n");
      out.write("                <p id=\"billing_country_field\" class=\"form-row form-row-wide address-field update_totals_on_change validate-required woocommerce-validated\">\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                <p id=\"billing_first_name_field\" class=\"form-row form-row-first validate-required\">\r\n");
      out.write("                    <label class=\"\" for=\"billing_first_name\">Full Name <abbr title=\"required\" class=\"required\">*</abbr>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input type=\"text\" value=\"");
      out.print(u.getName());
      out.write("\" placeholder=\"\" id=\"billing_first_name\" name=\"billing_first_name\" class=\"input-text \">\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("                <div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("                <p id=\"billing_email_field\" class=\"form-row form-row-first validate-required validate-email\">\r\n");
      out.write("                    <label class=\"\" for=\"billing_email\">Email Address <abbr title=\"required\" class=\"required\">*</abbr>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input type=\"text\" value=\"");
      out.print(u.getEmail());
      out.write("\" placeholder=\"\" id=\"billing_email\" name=\"billing_email\" class=\"input-text \">\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</form> <!-- Closing form tag for the first form -->\r\n");
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("\r\n");
      out.write("                                <h3 id=\"order_review_heading\">Your order</h3>\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"order_review\" style=\"position: relative;\">\r\n");
      out.write("                                    <table class=\"shop_table\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th class=\"product-name\">Product</th>\r\n");
      out.write("                                                <th class=\"product-total\">Total</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            <tr class=\"cart_item\">\r\n");
      out.write("                                                <td class=\"product-name\">\r\n");
      out.write("                                                    Ship Your Idea <strong class=\"product-quantity\">× 1</strong> </td>\r\n");
      out.write("                                                <td class=\"product-total\">\r\n");
      out.write("                                                    <span class=\"amount\">£15.00</span> </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                        <tfoot>\r\n");
      out.write("\r\n");
      out.write("                                            <tr class=\"cart-subtotal\">\r\n");
      out.write("                                                <th>Cart Subtotal</th>\r\n");
      out.write("                                                <td><span class=\"amount\">£15.00</span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                            <tr class=\"shipping\">\r\n");
      out.write("                                                <th>Shipping and Handling</th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("\r\n");
      out.write("                                                    Free Shipping\r\n");
      out.write("                                                    <input type=\"hidden\" class=\"shipping_method\" value=\"free_shipping\" id=\"shipping_method_0\" data-index=\"0\" name=\"shipping_method[0]\">\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            <tr class=\"order-total\">\r\n");
      out.write("                                                <th>Order Total</th>\r\n");
      out.write("                                                <td><strong><span class=\"amount\">£15.00</span></strong> </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("\r\n");
      out.write("                                        </tfoot>\r\n");
      out.write("                                    </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <div id=\"payment\">\r\n");
      out.write("                                        <ul class=\"payment_methods methods\">\r\n");
      out.write("                                            <li class=\"payment_method_bacs\">\r\n");
      out.write("                                                <input type=\"radio\" data-order_button_text=\"\" checked=\"checked\" value=\"bacs\" name=\"payment_method\" class=\"input-radio\" id=\"payment_method_bacs\">\r\n");
      out.write("                                                <label for=\"payment_method_bacs\">Direct Bank Transfer </label>\r\n");
      out.write("                                                <div class=\"payment_box payment_method_bacs\">\r\n");
      out.write("                                                    <p>Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"payment_method_cheque\">\r\n");
      out.write("                                                <input type=\"radio\" data-order_button_text=\"\" value=\"cheque\" name=\"payment_method\" class=\"input-radio\" id=\"payment_method_cheque\">\r\n");
      out.write("                                                <label for=\"payment_method_cheque\">Cheque Payment </label>\r\n");
      out.write("                                                <div style=\"display:none;\" class=\"payment_box payment_method_cheque\">\r\n");
      out.write("                                                    <p>Please send your cheque to Store Name, Store Street, Store Town, Store State / County, Store Postcode.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"payment_method_paypal\">\r\n");
      out.write("                                                <input type=\"radio\" data-order_button_text=\"Proceed to PayPal\" value=\"paypal\" name=\"payment_method\" class=\"input-radio\" id=\"payment_method_paypal\">\r\n");
      out.write("                                                <label for=\"payment_method_paypal\">PayPal <img alt=\"PayPal Acceptance Mark\" src=\"https://www.paypalobjects.com/webstatic/mktg/Logo/AM_mc_vs_ms_ae_UK.png\"><a title=\"What is PayPal?\" onclick=\"javascript:window.open('https://www.paypal.com/gb/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;\" class=\"about_paypal\" href=\"https://www.paypal.com/gb/webapps/mpp/paypal-popup\">What is PayPal?</a>\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                                <div style=\"display:none;\" class=\"payment_box payment_method_paypal\">\r\n");
      out.write("                                                    <p>Pay via PayPal; you can pay with your credit card if you don’t have a PayPal account.</p>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"form-row place-order\">\r\n");
      out.write("\r\n");
      out.write("                                            <input type=\"submit\" data-value=\"Place order\" value=\"Place order\" id=\"place_order\" name=\"woocommerce_checkout_place_order\" class=\"button alt\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("                        </div>                       \r\n");
      out.write("                    </div>                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-top-area\">\r\n");
      out.write("        <div class=\"zigzag-bottom\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer-about-us\">\r\n");
      out.write("                        <h2>u<span>Stora</span></h2>\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>\r\n");
      out.write("                        <div class=\"footer-social\">\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-youtube\"></i></a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer-menu\">\r\n");
      out.write("                        <h2 class=\"footer-wid-title\">User Navigation </h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"\">My account</a></li>\r\n");
      out.write("                            <li><a href=\"\">Order history</a></li>\r\n");
      out.write("                            <li><a href=\"\">Wishlist</a></li>\r\n");
      out.write("                            <li><a href=\"\">Vendor contact</a></li>\r\n");
      out.write("                            <li><a href=\"\">Front page</a></li>\r\n");
      out.write("                        </ul>                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer-menu\">\r\n");
      out.write("                        <h2 class=\"footer-wid-title\">Categories</h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"\">Mobile Phone</a></li>\r\n");
      out.write("                            <li><a href=\"\">Home accesseries</a></li>\r\n");
      out.write("                            <li><a href=\"\">LED TV</a></li>\r\n");
      out.write("                            <li><a href=\"\">Computer</a></li>\r\n");
      out.write("                            <li><a href=\"\">Gadets</a></li>\r\n");
      out.write("                        </ul>                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer-newsletter\">\r\n");
      out.write("                        <h2 class=\"footer-wid-title\">Newsletter</h2>\r\n");
      out.write("                        <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>\r\n");
      out.write("                        <div class=\"newsletter-form\">\r\n");
      out.write("                            <input type=\"email\" placeholder=\"Type your email\">\r\n");
      out.write("                            <input type=\"submit\" value=\"Subscribe\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer-bottom-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8\">\r\n");
      out.write("                    <div class=\"copyright\">\r\n");
      out.write("                        <p>&copy; 2015 uCommerce. All Rights Reserved. <a href=\"http://www.freshdesignweb.com\" target=\"_blank\">freshDesignweb.com</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"footer-card-icon\">\r\n");
      out.write("                        <i class=\"fa fa-cc-discover\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-mastercard\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-paypal\"></i>\r\n");
      out.write("                        <i class=\"fa fa-cc-visa\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("    <!-- Latest jQuery form server -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap JS form CDN -->\r\n");
      out.write("    <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery sticky menu -->\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.sticky.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- jQuery easing -->\r\n");
      out.write("    <script src=\"js/jquery.easing.1.3.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Script -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
