/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-04-29 10:06:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cgm.hello_web_app.eitities.User;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1426003893000L));
    _jspx_dependants.put("jar:file:/C:/laptrinhlop/resfulweb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HelloWebApp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.cgm.hello_web_app.eitities.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
 
	    
	User auth =(User) request.getSession().getAttribute("auth");
	if(auth!=null){
		
		response.sendRedirect("home");
	}
      out.write("\r\n");
      out.write("	<!DOCTYPE html>\r\n");
      out.write("	<!--\r\n");
      out.write("		ustora by freshdesignweb.com\r\n");
      out.write("		Twitter: https://twitter.com/freshdesignweb\r\n");
      out.write("		URL: https://www.freshdesignweb.com/ustora/\r\n");
      out.write("	-->\r\n");
      out.write("	<html lang=\"en\">\r\n");
      out.write("	<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<title>Ustora Demo</title>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Google Fonts -->\r\n");
      out.write("	<link\r\n");
      out.write("		href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600'\r\n");
      out.write("		rel='stylesheet' type='text/css'>\r\n");
      out.write("	<link\r\n");
      out.write("		href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300'\r\n");
      out.write("		rel='stylesheet' type='text/css'>\r\n");
      out.write("	<link href='http://fonts.googleapis.com/css?family=Raleway:400,100'\r\n");
      out.write("		rel='stylesheet' type='text/css'>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Bootstrap -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Font Awesome -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Custom CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/owl.carousel.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("	<style>\r\n");
      out.write("	    /* CSS tùy chỉnh */\r\n");
      out.write("	    .container{\r\n");
      out.write("	     margin-top: 50px;\r\n");
      out.write("	    }\r\n");
      out.write("	    .card-header.text-center {\r\n");
      out.write("	    font-size: 50px;\r\n");
      out.write("	    font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	    .form-group {\r\n");
      out.write("	        font-size: 12px; /* Kích thước font */\r\n");
      out.write("	        padding: 10px 10px; /* Kích thước padding */\r\n");
      out.write("	        height: auto; /* Chiều cao */\r\n");
      out.write("	  \r\n");
      out.write("	    }\r\n");
      out.write("	    .form-group label{\r\n");
      out.write("	      \r\n");
      out.write("	      width:405px;\r\n");
      out.write("	      margin-left:355px;\r\n");
      out.write("	      font-weight: bold;\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("	    }\r\n");
      out.write("	    .form-group input{\r\n");
      out.write("	      height:55px;\r\n");
      out.write("	      width:405px;\r\n");
      out.write("	      margin-left:355px;\r\n");
      out.write("	       border: 1px solid black; /* Viền màu và độ rộng */\r\n");
      out.write("	    box-sizing: 1px; /* Phân biệt kích thước */\r\n");
      out.write("	    }\r\n");
      out.write("	 /* Trong CSS */\r\n");
      out.write("	.btn-signup {\r\n");
      out.write("	    width: 100px; /* Độ rộng mong muốn */\r\n");
      out.write("	    margin-left: auto; /* Canh chỉnh nút ở giữa trang */\r\n");
      out.write("	    margin-right: auto;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("	<!--[if lt IE 9]>\r\n");
      out.write("	      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("	      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("	    <![endif]-->\r\n");
      out.write("	  \r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	  <div class=\"container\">\r\n");
      out.write("	        <h2 class=\"text-center mb-4\">Sign Up</h2>\r\n");
      out.write("	           \r\n");
      out.write("	        <form action=\"signup\" method=\"post\">\r\n");
      out.write("	       \r\n");
      out.write("	            <div class=\"form-group\">\r\n");
      out.write("	                <label for=\"fullname\">Full Name</label>\r\n");
      out.write("	                <input type=\"text\" class=\"form-control\" id=\"fullname\" name=\"fullname\" required>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"form-group\">\r\n");
      out.write("	                <label for=\"email\">Email address</label>\r\n");
      out.write("	                <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"form-group\">\r\n");
      out.write("	                <label for=\"password\">Password</label>\r\n");
      out.write("	                <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" required>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"form-group\">\r\n");
      out.write("	                <label for=\"confirmPassword\">Confirm Password</label>\r\n");
      out.write("	                <input type=\"password\" class=\"form-control\" id=\"confirmPassword\" name=\"confirmPassword\" required>\r\n");
      out.write("	                <p class=\"text-danger\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mess}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <button type=\"submit\" class=\"btn btn-primary btn-block btn-signup\">Sign Up</button>\r\n");
      out.write("	        </form>\r\n");
      out.write("	    </div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		<!-- End footer bottom area -->\r\n");
      out.write("	\r\n");
      out.write("		<!-- Latest jQuery form server -->\r\n");
      out.write("		<script src=\"https://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("		<!-- Bootstrap JS form CDN -->\r\n");
      out.write("		<script\r\n");
      out.write("			src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("		<!-- jQuery sticky menu -->\r\n");
      out.write("		<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("		<script src=\"js/jquery.sticky.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("		<!-- jQuery easing -->\r\n");
      out.write("		<script src=\"js/jquery.easing.1.3.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("		<!-- Main Script -->\r\n");
      out.write("		<script src=\"js/main.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("		<!-- Slider -->\r\n");
      out.write("		<script type=\"text/javascript\" src=\"js/bxslider.min.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"js/script.slider.js\"></script>\r\n");
      out.write("	</body>\r\n");
      out.write("	</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
